### ISSUE TITLE
Unable to generate lorem ipsum

### ISSUE THREAD

**Issue by wirtzdan** [tillkruss/alfred-lorem-ipsum#6] opened 2021-11-19 08:04 UTC
I have this strange bug, that I can't choose one of the options anymore. 

It always brings me to the search. 

Video: 
https://cln.sh/nIW3Yw

![CleanShot 2021-11-19 at 09 04 05](https://user-images.githubusercontent.com/18514829/142587236-cf7903f6-1e27-4b9c-bf1b-91fa20dd9e9d.png)

Any idea how to solve this?

**Comment by rverrips** [comment] 2021-11-19 17:10
I had this exact issue a few days ago and Till released a new version to fix it.
Which version are you running?

https://github.com/tillkruss/alfred-lorem-ipsum/issues/5

**Comment by ruudvanham** [comment] 2021-12-03 08:02
Same issue here, just updated alfred and imported the latest workflow. v0.2.1

**Comment by rverrips** [comment] 2021-12-03 16:20
Just to confirm @ruudvanham - you are saying your issue was fixed by using the latest version (v0.2.1) of the workflow? 

Also, @wirtzdan :  Is your issue resolved with the update to v0.2.1?

**Comment by tillkruss** [comment] 2021-12-03 16:49
I'm confused too.

**Comment by ruudvanham** [comment] 2021-12-03 18:34
No sorry, i'm still having the issue, even after updating alfred and the workflow to the latest versions

**Comment by tillkruss** [comment] 2021-12-03 19:01
What's your Alfred and macOS version?

**Comment by ruudvanham** [comment] 2021-12-06 08:47
Alfred: v4.6.1 [1274]
Lorem Ipsum: v0.2.1
MacOs: Monterey 12.0.1

**Comment by cgpro** [comment] 2021-12-08 18:36
Same issue here. If I type "lor" and accept the first option "paragraphs" a google search will be started.

**Comment by tillkruss** [comment] 2021-12-08 18:51
@ruudvanham @cgpro Are you two on Intel or M1 chips?

Do you have have PHP installed via Homebrew?

**Comment by cgpro** [comment] 2021-12-08 18:53
Nope:
macOS MOnterey (12.0.1)
iMac (Retina 5K i7 end 2015)

`$ php -v
PHP 7.4.12 (cli) (built: Nov 30 2020 13:28:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies`

Don't know how I installed this PHP-Version.

**Comment by tillkruss** [comment] 2021-12-09 01:33
Could you run `which php` for me to reveal the path?

**Comment by tillkruss** [comment] 2021-12-09 17:50
Can you go into your workflow and try this script instead?

```bash
if [ -f "/opt/homebrew/bin/php" ]; then
    /opt/homebrew/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php loremipsum.php "words" "{query}"
else
    php loremipsum.php "words" "{query}"
fi
```

**Comment by cgpro** [comment] 2021-12-09 18:38
Nope, after typing 'lorem words' alfred want to perform a google search.

![Bildschirmfoto 2021-12-09 um 19 36 46](https://user-images.githubusercontent.com/1557147/145455731-e232d754-c21f-42f9-b614-ad2d60208fe7.png)

If you want, we can do a call with screen sharing, if you can't reproduce it. Maybe its a setting? (not changed/updated after an update maybe)

**Comment by tillkruss** [comment] 2021-12-10 17:08
When you debug the workflow in Alfred, are you seeing any errors?

<img width="1372" alt="Screen Shot 2021-12-10 at 9 07 41 AM" src="https://user-images.githubusercontent.com/665029/145613568-923f28de-9bb5-469a-b0e0-18a1f27f9226.png">

**Comment by cgpro** [comment] 2021-12-10 19:35
This works in combination Language /bin/zsh (and not bin/bash)

`if [ -f "/opt/homebrew/bin/php" ]; then
    /opt/homebrew/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php loremipsum.php "words" "{query}"
else
    /Applications/MAMP/bin/php/php7.4.12/bin/php loremipsum.php "words" "{query}"
fi`

**Comment by tillkruss** [comment] 2021-12-14 18:19
@cgpro: Can you post the raw output of `which php`? Ideally a screenshot of your terminal?

**Comment by cgpro** [comment] 2021-12-14 19:17
![Bildschirmfoto 2021-12-14 um 20 16 52](https://user-images.githubusercontent.com/1557147/146064703-817e09ce-49fa-4092-a882-a86e445a1d7d.png)

**Comment by nicooprat** [comment] 2022-01-04 09:23
I had to manually replace the script PHP location:

```
% which php
/opt/homebrew/opt/php@7.4/bin/php
```

![image](https://user-images.githubusercontent.com/645641/148037061-71eb967f-3439-4f3d-b059-14c077069e41.png)

I'm not familiar with bash scripts, but it would be better to avoid hardcoding every possible PHP location in the script itself... Can't we use the output of `which php` to use it right away?

Anyway for now it works again, hope it helps.

**Comment by tillkruss** [comment] 2022-01-04 16:53
@nicooprat: I don't think we can, but we can use it as the fallback.

```bash
if [ -f "/opt/homebrew/bin/php" ]; then
    /opt/homebrew/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php loremipsum.php "words" "{query}"
else
    php loremipsum.php "words" "{query}"
fi
```

Can you give this one a try if it works?

**Comment by rverrips** [comment] 2022-01-05 21:14
This might be an option - I tested with this on my Mac and it worked ok.  

Should however add an else for error catching.  

```bash
if [ -f "$(which php)" ]; then
    $(which php) loremipsum.php "words" "{query}"
fi

**Comment by nicooprat** [comment] 2022-01-06 09:12
@rverrips Could you explain what you did exactly? I just tried it (with bash & zsh), but with no luck:

```zsh
$(which php) loremipsum.php "words" "{query}"
```

![image](https://user-images.githubusercontent.com/645641/148358543-250ecda3-7ee1-4716-9777-76894408446a.png)

**Comment by tillkruss** [comment] 2022-01-06 17:08
@rverrips `/bin/bash` may not have `php` in its `PATH`.

**Comment by tillkruss** [comment] 2022-01-06 17:09
I wonder if this would cover enough cases:

```bash
if [ -f "/opt/homebrew/bin/php" ]; then
    /opt/homebrew/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php loremipsum.php "words" "{query}"
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php loremipsum.php "words" "{query}"
elif [ -f "$(which php)" ]; then
    $(which php) loremipsum.php "words" "{query}"
else
	php loremipsum.php "words" "{query}"
fi
```

**Comment by rverrips** [comment] 2022-01-06 20:11
> @rverrips Could you explain what you did exactly? I just tried it (with bash & zsh), but with no luck:
> 
> ```shell
> $(which php) loremipsum.php "words" "{query}"
> ```
> 
> ![image](https://user-images.githubusercontent.com/645641/148358543-250ecda3-7ee1-4716-9777-76894408446a.png)

Apologies @nicooprat and @tillkruss  ... My hope was that ` $(which php)` would execute the string returned from (which php), i.e. current php binary.  

This works in "regular" bash, sh and zsh, but seems this does not work within the Alfred script execution - Apologies for the [wild goose chase](https://en.wiktionary.org/wiki/wild-goose_chase)

Like the issues we have with various paths to php, it seems Alfred can't find ```which``` either ... *sigh* 

(Please disregard my suggestion to use ```$(which php)```)

**Comment by tillkruss** [comment] 2022-01-06 20:15
The `/bin/bash` used by Alfred seems capable of `which php` and `command -v php`, but `php` may not be in the bash path.

**Comment by tillkruss** [comment] 2022-01-24 16:58
I've tweaked this in v0.2.2. Please re-open if the issue persists.

**Closed by tillkruss** 2022-01-24 16:58 UTC
